version: '3.3'

services:
  php_cli:
    container_name: test_blocks.php
    build:
      context: ../images/php-cli
    image: test_blocks_php
    working_dir: /usr/share/test/blocks
    volumes:
      - ../../test_php:/usr/share/test/blocks
    ports:
      - "8001:8001"
    networks:
      - tests_blocks
      
networks:
  tests_blocks:
